"use client";
import { useEffect, useState } from "react";
import Topbar from "@/components/Topbar";
import ExportButtons from "@/components/ExportButtons";
import { Sparkles, Loader2, FileText } from "lucide-react";

type Report = { id: string; type: string; title: string; content: string; generatedAt: string };

export default function ReportsPage() {
  const [reports, setReports] = useState<Report[]>([]);
  const [active, setActive] = useState<Report | null>(null);
  const [generating, setGenerating] = useState<string | null>(null);

  async function load() {
    const data = await fetch("/api/reports").then((r) => r.json());
    setReports(Array.isArray(data) ? data : []);
  }

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    load();
  }, []);

  async function generate(type: string) {
    setGenerating(type);
    const res = await fetch("/api/reports/generate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ type }),
    });
    setGenerating(null);
    if (res.ok) {
      const report = await res.json();
      await load();
      setActive(report);
    }
  }

  return (
    <div>
      <Topbar
        title="Reports"
        subtitle="Weekly status reports and steering committee packs, generated by the AI PM"
        action={
          <div className="flex gap-2">
            <button
              onClick={() => generate("WEEKLY_STATUS")}
              disabled={generating === "WEEKLY_STATUS"}
              className="flex items-center gap-1.5 text-sm px-3 py-2 rounded-lg bg-accent-50 text-accent-600 hover:bg-accent-100 disabled:opacity-50"
            >
              {generating === "WEEKLY_STATUS" ? <Loader2 size={15} className="animate-spin" /> : <Sparkles size={15} />}
              Weekly report now
            </button>
            <button
              onClick={() => generate("STEERING_COMMITTEE")}
              disabled={generating === "STEERING_COMMITTEE"}
              className="flex items-center gap-1.5 text-sm px-3 py-2 rounded-lg bg-accent-600 text-white shadow-sm shadow-accent-600/20 transition-colors hover:bg-accent-700 disabled:opacity-50"
            >
              {generating === "STEERING_COMMITTEE" ? <Loader2 size={15} className="animate-spin" /> : <Sparkles size={15} />}
              Steering pack now
            </button>
          </div>
        }
      />
      <div className="p-8 grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-1 bg-white rounded-xl border border-slate-200/70 shadow-sm shadow-slate-200/60 overflow-hidden">
          <div className="px-4 py-3 border-b border-slate-100">
            <p className="text-sm font-semibold text-slate-900">History</p>
          </div>
          <div className="max-h-[60vh] overflow-y-auto">
            {reports.map((r) => (
              <button
                key={r.id}
                onClick={() => setActive(r)}
                className={`w-full text-left px-4 py-3 border-b border-slate-50 hover:bg-slate-50 flex items-start gap-2 ${active?.id === r.id ? "bg-accent-50" : ""}`}
              >
                <FileText size={15} className="text-slate-400 mt-0.5 shrink-0" />
                <div>
                  <p className="text-sm font-medium text-slate-800">{r.title}</p>
                  <p className="text-xs text-slate-400">{r.type === "STEERING_COMMITTEE" ? "Steering committee" : "Weekly status"}</p>
                </div>
              </button>
            ))}
            {reports.length === 0 && (
              <p className="text-sm text-slate-400 text-center py-8 px-4">
                No reports yet — generate one now, or wait for the scheduled run configured in Admin settings.
              </p>
            )}
          </div>
        </div>
        <div className="lg:col-span-2 bg-white rounded-xl border border-slate-200/70 shadow-sm shadow-slate-200/60 p-5">
          {active ? (
            <>
              <div className="flex items-center justify-between mb-4">
                <div>
                  <p className="text-sm font-semibold text-slate-900">{active.title}</p>
                  <p className="text-xs text-slate-400">
                    {active.type === "STEERING_COMMITTEE" ? "Steering committee" : "Weekly status"}
                  </p>
                </div>
                <ExportButtons endpoint={`/api/reports/${active.id}`} filenamePrefix="portfolio-report" />
              </div>
              <div className="whitespace-pre-wrap text-sm text-slate-700 leading-relaxed">{active.content}</div>
            </>
          ) : (
            <p className="text-sm text-slate-400">Select a report from the list, or generate a new one.</p>
          )}
        </div>
      </div>
    </div>
  );
}
