export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50 px-4 py-10">
      <div className="max-w-2xl mx-auto bg-white rounded-xl border border-slate-200 p-8 space-y-6 text-sm text-slate-700 leading-relaxed">
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 text-xs text-amber-800">
          This is a template, not legal advice. It has not been reviewed by a lawyer. Have a licensed
          attorney review and adapt these terms — including liability limits and governing law — for
          your business, jurisdiction, and how you actually operate this product before publishing it.
        </div>

        <div>
          <h1 className="text-lg font-semibold text-slate-900 mb-1">Terms of service</h1>
          <p className="text-xs text-slate-400">Last updated: [DATE] · Replace bracketed placeholders before publishing.</p>
        </div>

        <section>
          <h2 className="font-medium text-slate-900 mb-1">1. Acceptance</h2>
          <p>By accessing or using this application, you agree to these terms. If you&apos;re using it on behalf of an organization, you&apos;re confirming you have authority to bind that organization.</p>
        </section>

        <section>
          <h2 className="font-medium text-slate-900 mb-1">2. The service</h2>
          <p>This application helps teams track projects, tasks, budgets, risks, and status, and offers optional AI-assisted planning, drafting, and reporting features. It is provided &quot;as is&quot; without warranty of any kind, express or implied, including fitness for a particular purpose or non-infringement.</p>
        </section>

        <section>
          <h2 className="font-medium text-slate-900 mb-1">3. AI-generated content</h2>
          <p>Plans, task breakdowns, effort estimates, charters, and reports generated by the AI assistant are drafting aids only. They may be inaccurate, incomplete, or unsuitable for your situation. You are solely responsible for reviewing and validating any AI-generated content before acting on it, especially for budget, staffing, legal, or compliance decisions.</p>
        </section>

        <section>
          <h2 className="font-medium text-slate-900 mb-1">4. User accounts & roles</h2>
          <p>You&apos;re responsible for safeguarding your login credentials and for all activity under your account. Administrators are responsible for assigning appropriate roles and access to their team members.</p>
        </section>

        <section>
          <h2 className="font-medium text-slate-900 mb-1">5. Acceptable use</h2>
          <p>Don&apos;t use the service to store or process data you don&apos;t have the right to store, to violate any law, or to attempt to disrupt or gain unauthorized access to the service.</p>
        </section>

        <section>
          <h2 className="font-medium text-slate-900 mb-1">6. Limitation of liability</h2>
          <p>To the maximum extent permitted by law, [YOUR COMPANY NAME] is not liable for indirect, incidental, special, or consequential damages, or for any loss of profits, data, or business arising from use of the service, including reliance on AI-generated content.</p>
        </section>

        <section>
          <h2 className="font-medium text-slate-900 mb-1">7. Changes</h2>
          <p>We may update these terms from time to time. Continued use of the service after changes take effect constitutes acceptance of the updated terms.</p>
        </section>

        <section>
          <h2 className="font-medium text-slate-900 mb-1">8. Governing law</h2>
          <p>These terms are governed by the laws of [JURISDICTION], without regard to conflict-of-law principles.</p>
        </section>

        <section>
          <h2 className="font-medium text-slate-900 mb-1">9. Contact</h2>
          <p>Questions about these terms: [CONTACT EMAIL].</p>
        </section>
      </div>
    </div>
  );
}
